export interface BootstrapStatistics {

    /**
     * Number of manifest files discovered.
     */
    manifestFilesDiscovered: number;

    /**
     * Number of manifest files successfully loaded.
     */
    manifestFilesParsed: number;

    /**
     * Number of tokens generated by the lexer.
     */
    tokensGenerated: number;

    /**
     * Number of directory specifications discovered.
     */
    directoriesDiscovered: number;

    /**
     * Number of file specifications discovered.
     */
    filesDiscovered: number;

    /**
     * Number of diagnostics generated.
     */
    diagnosticsGenerated: number;

    /**
     * Total execution time in milliseconds.
     */
    executionTimeMs: number;

}